import json
import logging
from pathlib import Path
from typing import Dict, List, Set, Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Type Hierarchy Lattice (Phase 5.2)
# ---------------------------------------------------------------------------
# The lattice captures a partial order of type relationships (e.g., class
# inheritance, interface implementation). It is constructed from the symbol index
# generated by ``SymbolIDEngine``. Each symbol entry should contain a ``type``
# field ("class", "interface", etc.) and an optional ``inherits`` list of fully
# qualified parent type names.
# ---------------------------------------------------------------------------

class TypeHierarchyLattice:
    """Mutable lattice representing type inheritance relationships.

    Nodes are type identifiers (the ``name`` field from the symbol index). Edges
    point from *child* → *parent* (subclass → superclass).
    """

    def __init__(self) -> None:
        # child -> set(parents)
        self._parents: Dict[str, Set[str]] = {}
        # parent -> set(children)
        self._children: Dict[str, Set[str]] = {}

    # ---------------------------------------------------------------------
    # Mutating API
    # ---------------------------------------------------------------------
    def add_type(self, name: str, bases: List[str] | None = None) -> None:
        """Add a type node and optional parent edges.

        Parameters
        ----------
        name:
            Unique identifier for the type (e.g., ``MyClass`` or ``pkg.Mod``).
        bases:
            Iterable of parent type names. If ``None`` or empty, the node is a
            root in the lattice.
        """
        if name not in self._parents:
            self._parents[name] = set()
        if bases:
            self._parents[name].update(bases)
            for base in bases:
                self._children.setdefault(base, set()).add(name)
                # Ensure the base node exists in the parents dict.
                self._parents.setdefault(base, set())
        else:
            # Ensure the node exists even if it has no parents.
            self._parents.setdefault(name, set())

    # ---------------------------------------------------------------------
    # Query API
    # ---------------------------------------------------------------------
    def ancestors(self, name: str) -> Set[str]:
        """Return the transitive set of ancestors for *name*.
        """
        visited: Set[str] = set()
        stack = list(self._parents.get(name, []))
        while stack:
            cur = stack.pop()
            if cur not in visited:
                visited.add(cur)
                stack.extend(self._parents.get(cur, []))
        return visited

    def descendants(self, name: str) -> Set[str]:
        """Return the transitive set of descendants for *name*.
        """
        visited: Set[str] = set()
        stack = list(self._children.get(name, []))
        while stack:
            cur = stack.pop()
            if cur not in visited:
                visited.add(cur)
                stack.extend(self._children.get(cur, []))
        return visited

    def topological_sort(self) -> List[str]:
        """Return a list of type names ordered from roots to leaves.
        Raises ``RuntimeError`` if a cycle is detected.
        """
        # Kahn's algorithm
        in_degree: Dict[str, int] = {node: len(parents) for node, parents in self._parents.items()}
        zero = [n for n, deg in in_degree.items() if deg == 0]
        order: List[str] = []
        while zero:
            node = zero.pop()
            order.append(node)
            for child in self._children.get(node, []):
                in_degree[child] -= 1
                if in_degree[child] == 0:
                    zero.append(child)
        if len(order) != len(self._parents):
            raise RuntimeError("Cycle detected in type hierarchy lattice")
        return order

    def to_dict(self) -> Dict[str, List[str]]:
        """Serialise the lattice as ``child -> [parents]`` mapping.
        """
        return {node: list(parents) for node, parents in self._parents.items()}

# ---------------------------------------------------------------------------
# Helper to build the lattice from a symbol index JSON file.
# ---------------------------------------------------------------------------

def build_type_hierarchy_from_index(index_path: Path) -> TypeHierarchyLattice:
    """Load ``symbol_index.json`` and construct a ``TypeHierarchyLattice``.

    The JSON file should be a list of symbol dictionaries as produced by
    ``SymbolIDEngine.dump_to_json``. Each symbol may contain an optional
    ``"inherits"`` field – a list of parent type names. If absent, the symbol is a
    root.
    """
    lattice = TypeHierarchyLattice()
    if not index_path.is_file():
        logger.warning("Symbol index not found at %s", index_path)
        return lattice
    try:
        with index_path.open("r", encoding="utf-8") as f:
            symbols: List[Dict[str, Any]] = json.load(f)
    except Exception as exc:
        logger.error("Failed to load symbol index %s: %s", index_path, exc)
        return lattice

    for sym in symbols:
        name = sym.get("name")
        if not name:
            continue
        bases = sym.get("inherits")
        if isinstance(bases, str):
            bases = [bases]
        elif not isinstance(bases, list):
            bases = []
        lattice.add_type(name, bases)
    return lattice

def get_type_hierarchy(repo_root: Path) -> TypeHierarchyLattice:
    """Convenience factory that looks for ``symbol_index.json`` at the repo root.
    """
    index_path = repo_root.resolve() / "symbol_index.json"
    return build_type_hierarchy_from_index(index_path)
